#!/bin/bash
# JWT Authentication System - Testing Guide
# Complete demonstration of all security features

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         JWT AUTHENTICATION SYSTEM - TEST CREDENTIALS         ║"
echo "║                  (Bcrypt HS256/HS512 Secured)                ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "📝 TEST USER ACCOUNTS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Admin User:"
echo "  Username:  admin"
echo "  Email:     admin@acme.com"
echo "  Password:  admin123"
echo "  Role:      admin"
echo "  Status:    approved"
echo ""
echo "Manager User:"
echo "  Username:  manager"
echo "  Email:     manager@acme.com"
echo "  Password:  manager123"
echo "  Role:      manager"
echo "  Status:    approved"
echo ""
echo "Regular User:"
echo "  Username:  user"
echo "  Email:     user@acme.com"
echo "  Password:  user123"
echo "  Role:      user"
echo "  Status:    approved"
echo ""
echo "Super Admin User:"
echo "  Username:  superadmin"
echo "  Email:     superadmin@test.com"
echo "  Password:  superadmin123"
echo "  Role:      super_admin"
echo "  Status:    approved"
echo ""

echo "🔐 SECURITY FEATURES IMPLEMENTED:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. JWT Encryption (HS256/HS512)"
echo "   ✅ Access tokens: HS256 (15-minute expiry)"
echo "   ✅ Refresh tokens: HS512 (30-day expiry)"
echo "   ✅ Token type validation (prevent token substitution)"
echo "   ✅ Explicit algorithm enforcement"
echo ""
echo "2. Brute-Force Protection"
echo "   ✅ IP-based rate limiting: 5 attempts per 15 minutes"
echo "   ✅ Account lockout: 3 failed logins = 15-minute lock"
echo "   ✅ Automatic reset on successful login"
echo "   ✅ Failed attempt tracking with counters"
echo ""
echo "3. Token Revocation"
echo "   ✅ Blacklist storage with TTL index (auto-cleanup)"
echo "   ✅ Immediate logout across all devices"
echo "   ✅ Token family tracking (detects compromised chains)"
echo "   ✅ Per-device token revocation"
echo ""
echo "4. Session Management"
echo "   ✅ Multi-device support with device tracking"
echo "   ✅ Device fingerprinting (screen, timezone, platform)"
echo "   ✅ List active sessions endpoint"
echo "   ✅ Revoke specific device endpoint"
echo "   ✅ Logout all devices functionality"
echo ""
echo "5. Audit & Monitoring"
echo "   ✅ Complete login attempt history"
echo "   ✅ Track IP address and device ID"
echo "   ✅ Suspicious activity detection"
echo "   ✅ Automatic cleanup of expired records (hourly)"
echo ""

echo "📊 API ENDPOINTS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Authentication:"
echo "  POST   /api/auth/login          (public, rate-limited)"
echo "  POST   /api/auth/logout         (protected)"
echo "  GET    /api/auth/me             (protected)"
echo "  POST   /api/auth/refresh        (protected)"
echo ""
echo "Session Management:"
echo "  GET    /api/sessions/sessions   (protected) - List devices"
echo "  DELETE /api/sessions/:device_id (protected) - Revoke device"
echo "  POST   /api/sessions/revoke-others      (protected) - Logout others"
echo "  POST   /api/sessions/:id/trust          (protected) - Trust device"
echo "  GET    /api/sessions/login-history      (protected) - Audit log"
echo "  GET    /api/sessions/suspicious-activity (protected) - Alerts"
echo "  POST   /api/sessions/logout-all-devices (protected) - Complete logout"
echo ""

echo "🗄️  DATABASE MODELS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "New Collections Created:"
echo "  ✅ TokenBlacklist          - Revoked tokens with TTL cleanup"
echo "  ✅ LoginAudit              - Complete login attempt history"
echo "  ✅ TokenSessionDevice      - Multi-device session tracking"
echo ""
echo "Enhanced Models:"
echo "  ✅ User                    - Added security tracking fields"
echo "  ✅ RefreshToken            - Added device/family tracking"
echo ""

echo "⚙️  CONFIGURATION:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Environment Variables (.env):"
echo "  ACCESS_TOKEN_SECRET=<32+ byte key>    (HS256)"
echo "  REFRESH_TOKEN_SECRET=<32+ byte key>   (HS512)"
echo "  RATE_LIMIT_ATTEMPTS=5                 (per IP)"
echo "  RATE_LIMIT_WINDOW_MINUTES=15"
echo "  MAX_FAILED_ATTEMPTS=3                 (account lockout)"
echo "  ACCOUNT_LOCK_DURATION_MINUTES=15"
echo "  BCRYPT_ROUNDS=12"
echo ""
echo "Run: npm start   (to start the server)"
echo "Run: npm run dev (to start with auto-reload)"
echo ""

echo "✅ VERIFICATION STEPS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Test successful login:"
echo "   curl -X POST http://localhost:3000/api/auth/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"username\":\"admin\",\"password\":\"admin123\"}'"
echo ""
echo "2. Test invalid password (triggers rate limiting after 5 attempts)"
echo "3. Test account lockout (3+ failed attempts = 15 min lock)"
echo "4. Test session listing: /api/sessions/sessions"
echo "5. Test login history: /api/sessions/login-history"
echo "6. Test suspicious activity: /api/sessions/suspicious-activity"
echo ""

echo "🔍 SECURITY CHECKLIST:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Passwords: Bcrypt hashed (12 salt rounds, never stored plaintext)"
echo "✅ Tokens: HTTP-only cookies (XSS protection)"
echo "✅ Encryption: HS256/HS512 algorithms enforced"
echo "✅ Rate Limiting: IP and account-based protection"
echo "✅ Revocation: Immediate token blacklist"
echo "✅ Audit Trail: All login attempts logged"
echo "✅ Device Tracking: Multi-device support"
echo "✅ Session Management: Per-device revocation"
echo "✅ Cleanup: Automatic token/record expiry"
echo "✅ Validation: Token type prevents substitution"
echo ""

echo "📖 PASSWORD INFORMATION:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "The 'Invalid credentials' error during login means:"
echo "  1. Username not found, OR"
echo "  2. Password doesn't match the bcrypt hash in database"
echo ""
echo "To reset a password, run:"
echo "  node server/utils/mongo/create-test-user.js"
echo ""
echo "This script:"
echo "  ✓ Uses bcrypt with 12 salt rounds"
echo "  ✓ Works with MongoDB"
echo "  ✓ Creates/updates test users with known passwords"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "              System Ready for Authentication Testing!"
echo "═══════════════════════════════════════════════════════════════"
echo ""
